###############################################################################
# BINARY SENSORS
###############################################################################

# NOISE SENSOR

- platform: ffmpeg_noise
  name: "Zoë noise"
  input: !secret nursery_camera_rtsp
  extra_arguments: -filter:a highpass=f=300,lowpass=f=2500,volume=volume=2 -nostats
  initial_state: true
  duration: 2
  reset: 60
  peak: -30 # 0 is very loud and -100 is low.

# WORKDAY CALENDAR

- platform: workday
  country: NL

# PING NETWORK DEVICES

- platform: ping
  host: 192.168.2.38
  name: "Sprinkler controller"
  scan_interval: 30

- platform: ping
  host: 192.168.2.194
  name: "Bedroom home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.14
  name: "Livingroom home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.30
  name: "Hue utility bridge"
  scan_interval: 30

- platform: ping
  host: 192.168.2.34
  name: "Opentherm controller"
  scan_interval: 30

- platform: ping
  host: 192.168.2.32
  name: "Dining room home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.196
  name: "Scullery range extender"
  scan_interval: 30

- platform: ping
  host: 192.168.2.10
  name: "Pi-Hole"
  scan_interval: 30

- platform: ping
  host: 192.168.2.1
  name: "Fritz!Box"
  scan_interval: 30

- platform: ping
  host: 192.168.2.36
  name: "Noenoe"
  scan_interval: 30

- platform: ping
  host: 192.168.2.51
  name: "Soapie"
  scan_interval: 30

- platform: ping
  host: 192.168.2.54
  name: "Kids camera"
  scan_interval: 30

- platform: ping
  host: 192.168.2.48
  name: "Livingroom FRITZ!Powerline"
  scan_interval: 30
