###############################################################################
# BINARY SENSORS
###############################################################################

# Combine downstairs doors and windows
- platform: group
  name: "Beneden deuren en ramen"
  entities:
    - binary_sensor.eetkamer_raam
    - binary_sensor.kitchen_door

# PING NETWORK DEVICES

- platform: ping
  host: 192.168.2.38
  name: "OpenSprinkler"
  scan_interval: 30

- platform: ping
  host: 192.168.2.194
  name: "Slaapkamer home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.19
  name: "Woonkamer home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.30
  name: "Hue bridge"
  scan_interval: 30

- platform: ping
  host: 192.168.2.34
  name: "Opentherm besturing"
  scan_interval: 30

- platform: ping
  host: 192.168.2.32
  name: "Eetkamer home mini"
  scan_interval: 30

- platform: ping
  host: 192.168.2.196
  name: "Bijkeuken range extender"
  scan_interval: 30

- platform: ping
  host: 192.168.2.10
  name: "Pi-Hole"
  scan_interval: 30

- platform: ping
  host: 192.168.2.1
  name: "Fritz!Box"
  scan_interval: 30

- platform: ping
  host: 192.168.2.36
  name: "Noenoe"
  scan_interval: 30

- platform: ping
  host: 192.168.2.59
  name: "Soapie"
  scan_interval: 30

- platform: ping
  host: 192.168.2.54
  name: "Zoë camera"
  scan_interval: 30

- platform: ping
  host: 192.168.2.48
  name: "Beneden FRITZ!Powerline"
  scan_interval: 30

- platform: ping
  host: 192.168.2.26
  name: "Boven FRITZ!Powerline"
  scan_interval: 30

- platform: ping
  host: 192.168.2.47
  name: "Meterkast FRITZ!Powerline"
  scan_interval: 30

- platform: ping
  host: 192.168.2.31
  name: "Media server"
  scan_interval: 30
