###############################################################################
# GENERAL
###############################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Include customization file and packages
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages/

# Inclusions
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
alarm_control_panel: !include alarm_control_panel.yaml
sensor: !include sensor.yaml
recorder: !include recorder.yaml
shell_command: !include shell_command.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
plant: !include plant.yaml

# Enable themes
frontend:
  themes: !include_dir_merge_named themes

http:
  # Limit login attempts
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

###############################################################################
# SPOTIFY
###############################################################################

# Integration for playing Spotify on Chromecast/Google home.
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: NL

###############################################################################
# LOGGER
###############################################################################

logger:
  default: debug
  logs:
    pychromecast.socket_client: fatal
    homeassistant.components.webhook: error

  filters:

    # Ignore messages from the alarm panel
    homeassistant.components.zha.core.channels.base:
      - ".*received command get_panel_status"
      - ".*Arming all IAS ACE zones"

    homeassistant.helpers.entity:
      - ".*Update of binary_sensor.*"

###############################################################################
# ZIGBEE
###############################################################################

zha:
  zigpy_config:
    network:
      channel: 20

###############################################################################
# PRECENCE
###############################################################################

proximity:
  home_mike:
    zone: home
    devices:
      - device_tracker.sm_g960f
      - device_tracker.ping_phone_mike
    tolerance: 50
    unit_of_measurement: km
  home_anneloes:
    zone: home
    devices:
      - device_tracker.sm_a202f
      - device_tracker.ping_phone_anneloes
    tolerance: 50
    unit_of_measurement: km

device_tracker:

  # Presence based on ping
  - platform: ping
    hosts:
      ping_phone_mike: 192.168.2.11
      ping_phone_anneloes: 192.168.2.27

  # BT device tracker
  - platform: bluetooth_tracker

