###############################################################################
# GENERAL
###############################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Inclusions
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
alarm_control_panel: !include alarm_control_panel.yaml
media_player: !include media_player.yaml
utility_meter: !include utility_meter.yaml
sensor: !include sensor.yaml
recorder: !include recorder.yaml

# Enable themes
frontend:
  themes: !include_dir_merge_named themes

# Include customazation file
homeassistant:
  customize: !include customize.yaml
  
# Limit login attempts
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  
# Text to speech
tts:
  - platform: google_translate

###############################################################################
# ZIGBEE
###############################################################################

zha:
  zigpy_config:
    network:
      channel: 20
   
###############################################################################
# PRECENCE
###############################################################################

proximity:
  home_mike:
    zone: home
    devices:
      - device_tracker.phone_mike
      - device_tracker.ping_phone_mike
    tolerance: 50
    unit_of_measurement: km
  home_anneloes:
    zone: home
    devices:
      - device_tracker.sm_a202f
      - device_tracker.ping_phone_anneloes
    tolerance: 50
    unit_of_measurement: km
    
    
# Precence based on ping
device_tracker:
  - platform: ping
    hosts:
      ping_phone_mike: 192.168.2.23
      ping_phone_anneloes: 192.168.2.27
      