###############################################################################
# GENERAL
###############################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Inclusions
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
alarm_control_panel: !include alarm_control_panel.yaml
media_player: !include media_player.yaml
utility_meter: !include utility_meter.yaml
sensor: !include sensor.yaml
recorder: !include recorder.yaml
shell_command: !include shell_command.yaml

# Enable themes
frontend:
  themes: !include_dir_merge_named themes

# Include customization file
homeassistant:
  customize: !include customize.yaml

http:

  # Limit login attempts
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

###############################################################################
# INPUT SELECT
###############################################################################

input_select:

  # Manual override for house state
  house_state_override:
    name: House state override
    options:
      - auto
      - home
      - away
      - night
      - holiday
    initial: auto
    icon: mdi:home

  # Manual override for climate state
  climate_period_override:
    name: Climate period override
    options:
      - auto
      - morning
      - day
      - evening
      - night
    initial: auto
    icon: mdi:home-thermometer

###############################################################################
# INPUT NUMBER
###############################################################################

input_number:

  # Volume for alarm
  alarm_volume:
    name: Alarm volume
    icon: mdi:volume-high
    initial: 1
    min: 0
    max: 1
    step: 0.1
    mode: slider

  # Volume for pending and arming beep
  aux_volume:
    name: Aux volume
    icon: mdi:volume-medium
    initial: 0.4
    min: 0
    max: 1
    step: 0.1
    mode: slider

  # Sprinkler base time
  back_sprinkler_base_time:
    name: Back sprinkler base time
    icon: mdi:clock
    initial: 2
    min: 0
    max: 10
    step: 1
    unit_of_measurement: "min"
    mode: box

  # Sprinkler base time
  front_sprinkler_base_time:
    name: Front sprinkler base time
    icon: mdi:clock
    initial: 2
    min: 0
    max: 10
    step: 1
    unit_of_measurement: "min"
    mode: box

  # Sprinkler manual run time
  back_sprinkler_time:
    name: Back sprinkler time
    icon: mdi:clock
    initial: 2
    min: 0
    max: 10
    step: 0.1
    unit_of_measurement: "min"
    mode: box

  # Sprinkler manual run time
  front_sprinkler_time:
    name: Front sprinkler time
    icon: mdi:clock
    initial: 2
    min: 0
    max: 10
    step: 0.1
    unit_of_measurement: "min"
    mode: box

  # If rain is above this number no watering
  rain_threshold:
    name: Rain threshold
    icon: mdi:weather-pouring
    initial: 2
    min: 0
    max: 20
    step: 1
    unit_of_measurement: "mm"
    mode: box

  # Avarage humidity
  base_humidity:
    name: Base humidity
    icon: mdi:water-percent
    initial: 75
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: box

  # Avarage temperature
  base_temperature:
    name: Base temperature
    icon: mdi:thermometer
    initial: 75
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "°C"
    mode: box

  # Cutoff sprinkler entirely
  watering_cutoff:
    name: Watering cutoff
    icon: mdi:sprinkler-variant
    initial: 75
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: box

  # Temperature for hot water
  hot_water_temperature:
    name: Hot water temperature
    icon: mdi:water-pump
    initial: 60
    min: 45
    max: 85
    step: 1
    unit_of_measurement: "°C"
    mode: box

  # Night temperature
  night_temperature:
    name: Night temperature
    icon: mdi:thermometer
    initial: 15
    min: 0
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    mode: box

  # Day temperature
  day_temperature:
    name: Day temperature
    icon: mdi:thermometer
    initial: 16.5
    min: 0
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    mode: box

  # Evening temperature
  evening_temperature:
    name: Evening temperature
    icon: mdi:thermometer
    initial: 18.5
    min: 0
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    mode: box

  # Morning  temperature
  morning_temperature:
    name: Morning temperature
    icon: mdi:thermometer
    initial: 18
    min: 0
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    mode: box

  # Energy tariffs
  gas_tariff:
    name: Gas tariff
    icon: mdi:cash
    initial: 0.824567
    min: 0
    max: 500
    step: 0.000001
    unit_of_measurement: "€/m³"
    mode: box

  fixed_gas_tariff:
    name: Fixed gas tariff
    icon: mdi:cash
    initial: 251.85
    min: 0
    max: 500
    step: 0.01
    unit_of_measurement: "€/Year"
    mode: box

  fixed_energy_tariff:
    name: Fixed energy tariff
    icon: mdi:cash
    initial: -235.88
    min: -500
    max: 500
    step: 0.01
    unit_of_measurement: "€/Year"
    mode: box

  energy_tariff_1:
    name: Energy tariff off-peak
    icon: mdi:cash
    initial: 0.22748
    min: 0
    max: 100
    step: 0.000001
    unit_of_measurement: "€/kWh"
    mode: box

  energy_tariff_2:
    name: Energy tariff peak
    icon: mdi:cash
    initial: 0.22748
    min: 0
    max: 100
    step: 0.000001
    unit_of_measurement: "€/kWh"
    mode: box

###############################################################################
# INPUT DATETIME
###############################################################################

input_datetime:

  # Heating

  heating_pre_heat:
    name: Heating pre-heat
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:50"

  heating_early_stop:
    name: Heating early stop
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "02:00"

  floor_heating_pump_delay:
    name: Floor heating pump delay
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:30"

  # Hot water

  hot_water_pre_heat:
    name: Hot water pre-heat
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:15"

  hot_water_early_stop:
    name: Hot water early stop
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:30"

  # Time of day

  morning_end:
    name: Morning end
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "09:00"

  evening_start:
    name: Evening start
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "16:15"

  end_night_workday:
    name: End night - workday
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "05:30"

  start_night_workday:
    name: Start night - workday
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "21:00"

  end_night_free_day:
    name: End night - free day
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "07:00"

  start_night_free_day:
    name: Start night - free day
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "21:30"

  # Alarm

  night_alarm_delay:
    name: Night alarm delay
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:30"

  night_alarm_early_stop:
    name: Night alarm early stop
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:30"

  # Lights

  light_motion_timeout_short:
    name: Light motion timeout - short
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "00:15"

  light_motion_timeout_long:
    name: Light motion timeout - long
    icon: mdi:clock
    has_time: true
    has_date: false
    initial: "01:00"

###############################################################################
# INPUT BOOLEAN
###############################################################################

input_boolean:

  quiet:
    name: Quiet
    icon: mdi:volume-off

  holiday:
    name: Holiday
    icon: mdi:beach

  first_down:
    name: First down
    icon: mdi:motion-sensor

###############################################################################
# LOGGER
###############################################################################

logger:
  default: debug
  logs:
    pychromecast.socket_client: fatal
    homeassistant.components.webhook: error

  filters:

    # Ignore messages from the alarm panel
    homeassistant.components.zha.core.channels.base:
      - ".*received command get_panel_status"
      - ".*Arming all IAS ACE zones"
      - ".*Disarming all IAS ACE zones"

###############################################################################
# ZIGBEE
###############################################################################

zha:
  zigpy_config:
    network:
      channel: 20

###############################################################################
# PRECENCE
###############################################################################

proximity:
  home_mike:
    zone: home
    devices:
      - device_tracker.sm_g960f
      - device_tracker.ping_phone_mike
    tolerance: 50
    unit_of_measurement: km
  home_anneloes:
    zone: home
    devices:
      - device_tracker.sm_a202f
      - device_tracker.ping_phone_anneloes
    tolerance: 50
    unit_of_measurement: km

# Presence based on ping
device_tracker:
  - platform: ping
    hosts:
      ping_phone_mike: 192.168.2.11
      ping_phone_anneloes: 192.168.2.27
