###############################################################################
# MEDIA PLAYER
###############################################################################

# Whole house media group. Used for alarm panel.
- platform: group
  name: Speaker Group
  entities:
    - media_player.downstairs_speakers
    - media_player.bedroom_home_mini
