###############################################################################
# CLIMATE
###############################################################################

climate:

  # Thermostat
  - icon: mdi:water-boiler
    modes:
      - "off"
      - "heat"
    name: "Central heating"
    unique_id: "fQOTEYDCYf3jyVV2QJH2"
    current_temperature_topic: "opentherm-thermostat/current-temperature/get"
    mode_command_topic: "opentherm-thermostat/mode/set"
    mode_state_topic: "opentherm-thermostat/mode/get"
    temperature_command_topic: "opentherm-thermostat/setpoint-temperature/set"
    temperature_state_topic: "opentherm-thermostat/setpoint-temperature/get"
    min_temp: 12
    max_temp: 28
    value_template: "{{ value }}"
    temp_step: 0.5

  # Hot water
  - icon: mdi:water-pump
    modes:
      - "off"
      - "heat"
    name: "Hot water service"
    unique_id: "NIFQbOND7GFNzowcENAG"
    current_temperature_topic: "opentherm-thermostat/boiler-temperature/get"
    mode_command_topic: "opentherm-thermostat/dhw-state/set"
    mode_state_topic: "opentherm-thermostat/dhw-state/get"
    temperature_command_topic: "opentherm-thermostat/dhw-temperature/set"
    temperature_state_topic: "opentherm-thermostat/dhw-temperature/get"
    min_temp: 10
    max_temp: 80
    value_template: "{{ value }}"
    temp_step: 0.5
    mode_command_template: >-
      {% set values = { 'heat':'on', 'off':'off'} %}
      {{ values[value] if value in values.keys() else 'off' }}
    mode_state_template: >-
      {% set values = { 'on':'heat', 'off':'off'} %}
      {{ values[value] if value in values.keys() else 'off' }}

###############################################################################
# MQTT THERMOSTAT SENSORS
###############################################################################

sensor:

  - name: "Current thermostat temperature"
    device_class: temperature
    state_topic: "opentherm-thermostat/current-temperature/get"
    value_template: "{{ value }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  - name: "Target thermostat temperature"
    device_class: temperature
    state_topic: "opentherm-thermostat/setpoint-temperature/get"
    value_template: "{{ value }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  - name: "Boiler temperature"
    device_class: temperature
    state_topic: "opentherm-thermostat/boiler-temperature/get"
    value_template: "{{ value }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  - name: "Boiler target temperature"
    device_class: temperature
    state_topic: "opentherm-thermostat/boiler-target-temperature/get"
    value_template: "{{ value }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  - name: "Boiler mode"
    device_class: temperature
    state_topic: "opentherm-thermostat/mode/get"
    value_template: "{{ value }}"
    icon: mdi:water-boiler

  - name: "Water target temperature"
    device_class: temperature
    state_topic: "opentherm-thermostat/dhw-temperature/get"
    value_template: "{{ value }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  - name: "Water service"
    state_topic: "opentherm-thermostat/dhw-state/get"
    value_template: "{{ value }}"
    icon: mdi:water-boiler
