###############################################################################
# SWITCH
###############################################################################
   
# RPI cooling fan
- platform: rpi_gpio
  ports:
    14: RPI Cooling Fan