################################################################################
# SUBSTITUTIONS
################################################################################

substitutions:
  device_name: bluetooth-relay
  upper_devicename: Bluetooth-relay
  device_description: "Relays bluetooth signal."

###############################################################################
# GENERAL
###############################################################################

esphome:
  name: $device_name
  comment: "${device_description}"
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable ota update with a password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret esphome_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable webserver
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

# Used for Bluethooth proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:

binary_sensor:

  - platform: status
    name: "${upper_devicename} status"
    icon: "mdi:wifi"
