################################################################################
# SUBSTITUTIONS
################################################################################

substitutions:
  device_name: boiler
  upper_devicename: boiler
  device_description: "ESPHome version of the smart boiler control."

###############################################################################
# GENERAL
###############################################################################

esphome:
  name: $device_name
  comment: "${device_description}"
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable ota update with a password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret esphome_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable webserver
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

###############################################################################
# SPECIFIC
###############################################################################

binary_sensor:

  - platform: status
    name: "${device_name} status"
    icon: "mdi:wifi"
    
sensor:
  - platform: homeassistant
    id: downstairs_temperature
    entity_id: sensor.downstairs_temperature
    
  - platform: pid
    name: "PID Climate Result"
    type: RESULT
    
  - platform: pid
    name: "PID Climate Heat"
    type: HEAT
    
output:
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: sample_output
    
climate:
  - platform: pid
    name: "PID Climate Controller"
    sensor: downstairs_temperature
    default_target_temperature: 15째C
    heat_output: sample_output
    visual:
      min_temperature: 12 째C
      max_temperature: 25 째C
      temperature_step: 0.5 째C
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
