################################################################################
# SUBSTITUTIONS
################################################################################

substitutions:
  device_name: garage-door
  upper_devicename: garage-door
  device_description: "Controller for the garage door."

###############################################################################
# GENERAL
###############################################################################

esphome:
  name: $device_name
  comment: "${device_description}"
  platform: ESP8266
  board: esp01_1m 

# Enable logging
logger:

# Enable ota update with a password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret esphome_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable webserver
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

###############################################################################
# SPECIFIC
###############################################################################

status_led:
  pin: GPIO13

# Connect to RF receiver
remote_receiver:
  pin: GPIO2
  dump: 
    - rc_switch
    - rc5

binary_sensor:

  - platform: status
    name: "${device_name} status"
    icon: "mdi:wifi"

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 1"
    on_press:
      then:
        - switch.toggle: R1
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 2"
    on_press:
      then:
        - switch.toggle: R2
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 3"
    on_press:
      then:
        - switch.toggle: R3
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 4"
    on_press:
      then:
        - switch.toggle: R4

switch:
  - platform: gpio
    name: "Relay 1"
    pin: GPIO12
    id: R1
  - platform: gpio
    name: "Relay 2"
    pin: GPIO5
    id: R2
  - platform: gpio
    name: "Relay 3"
    pin: GPIO4
    id: R3
  - platform: gpio
    name: "Relay 4"
    pin: GPIO15
    id: R4
