---
################################################################################
# SUBSTITUTIONS
################################################################################

substitutions:
  device_name: reindeer
  upper_devicename: Reindeer
  device_description: "A simple reindeer light"

################################################################################
# GENERAL 
################################################################################

esphome:
  name: $device_name
  comment: "${device_description}"
  platform: ESP8266
  board: esp01_1m
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

# Enable ota update with a password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret esphome_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable webserver
web_server:
  port: 80

################################################################################
# SPECIFIC 
################################################################################

output:
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    output: pwm_output
    name: "Reindeer Light"

################################################################################
# STATUS SENSOR 
################################################################################

binary_sensor:
  - platform: status
    name: "${device_name} status"
    icon: "mdi:wifi"
