################################################################################
# SUBSTITUTIONS
################################################################################

substitutions:
  device_name: voortuin-sprinkler
  upper_devicename: Voortuin sprinkler
  device_description: "Sprinkler besturing voor de voortuin"

###############################################################################
# GENERAL
###############################################################################

esphome:
  name: $device_name
  comment: "${device_description}"
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable ota update with a password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret esphome_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable webserver
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

###############################################################################
# SPECIFIC
###############################################################################

binary_sensor:

  - platform: status
    name: "${upper_devicename} Status"
    icon: "mdi:wifi"
