name: Home Assistant CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2.4.0
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1.1.1

  remarklint:
    runs-on: ubuntu-18.04
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2.4.0
      - name: 🚀 remarklint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} configuration check"
    needs: [yamllint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2.4.0
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.1.1
        with:
          path: "."
          secrets: ./.stubs/secrets.yaml
          version: "${{ matrix.version }}"

  ESPHome:
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2.4.0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./esphome/
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./esphome -type f -name "*.yaml" -maxdepth 1 -not -name "secrets.yaml"); do esphome config "${file}"; done

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request'}}
    needs: [home-assistant, ESPHome]
    steps:
      - name: Github Action for curl
        uses: wei/curl@v1.1.1
        with:
          args: curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK }}
